drivers: pca9685: fix missing (void *) cast
This fixes following errors using native architecture:
  RIOT/drivers/pca9685/pca9685.c:42:15: error: format ‘%p’ expects
  argument of type ‘void *’, but argument 5 has type ‘const
  pca9685_params_t *’ [-Werror=format=]

Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>